from discord.commands import slash_command
from discord.ext.commands import Context
from discord.ext import commands
import discord.ext
import discord

wiki = "https://switchbrew.org/wiki/Error_codes"
error_codes = {
        "0xa01": "UnknownError",
        "0xc01": "UnknownError",
        "0xe01": "OutOfSessions",
        "0x1c01": "InvalidArgument",
        "0x4201": "NotImplemented",
        "0x6c01": "StopProcessingException",
        "0x7201": "NoSynchronizationObject",
        "0x7601": "TerminationRequested",
        "0x8c01": "NoEvent",
        "0x9401": "UnknownError",
        "0xca01": "InvalidSize",
        "0xcc01": "InvalidAddress",
        "0xce01": "OutOfResource",
        "0xd001": "OutOfMemory",
        "0xd201": "OutOfHandles",
        "0xd401": "InvalidCurrentMemory",
        "0xd801": "InvalidNewMemoryPermission",
        "0xda01": "UnknownError",
        "0xdc01": "InvalidMemoryRegion",
        "0xe001": "InvalidPriority",
        "0xe201": "InvalidCoreId",
        "0xe401": "InvalidHandle",
        "0xe601": "InvalidPointer",
        "0xe801": "InvalidCombination",
        "0xea01": "TimedOut",
        "0xec01": "Cancelled",
        "0xee01": "OutOfRange",
        "0xf001": "InvalidEnumValue",
        "0xf201": "NotFound",
        "0xf401": "Busy",
        "0xf601": "SessionClosed",
        "0xf801": "NotHandled",
        "0xfa01": "InvalidState",
        "0xfc01": "ReservedUsed",
        "0xfe01": "NotSupported",
        "0x10001": "Debug",
        "0x10201": "NoThread",
        "0x10401": "UnknownThread",
        "0x10601": "PortClosed",
        "0x10801": "LimitReached",
        "0x10a01": "InvalidMemoryPool",
        "0x20401": "ReceiveListBroken",
        "0x20601": "OutOfAddressSpace",
        "0x20801": "MessageTooLarge",
        "0x40001": "UnknownError",
        "0x40201": "UnknownError",
        "0x40401": "UnknownError",
        "0x40601": "UnknownError",
        "0x40801": "UnknownError",
        "0x40a01": "InvalidProcessId",
        "0x40c01": "InvalidThreadId",
        "0x40e01": "InvalidId",
        "0x41001": "ProcessTerminated",
        "0x7fe01": "UnknownError",
        "0x202": "ResultPathNotFound",
        "0x402": "ResultPathAlreadyExists",
        "0xe02": "ResultTargetLocked",
        "0x4602": "UsableSpaceNotEnoughMmcCalibration",
        "0x4802": "UsableSpaceNotEnoughMmcSafe",
        "0x4a02": "UsableSpaceNotEnoughMmcUser",
        "0x4c02": "UsableSpaceNotEnoughMmcSystem",
        "0x4e02": "ResultUsableSpaceNotEnoughSdCard",
        "0x6402": "ResultUnsupportedSdkVersion",
        "0x7802": "ResultMountNameAlreadyExists",
        "0x7d202": "ResultPartitionNotFound",
        "0x7d402": "ResultTargetNotFound",
        "0xfa202": "PortSdCardNoDevice",
        "0x13b002": "GameCardCardNotInserted",
        "0x13b402": "GameCardCardNotActivated",
        "0x13d802": "GameCardInvalidSecureAccess",
        "0x13da02": "GameCardInvalidNormalAccess",
        "0x13dc02": "GameCardInvalidAccessAcrossMode",
        "0x13e002": "GameCardInitialDataMismatch",
        "0x13e202": "GameCardInitialNotFilledWithZero",
        "0x13e402": "GameCardKekIndexMismatch",
        "0x13ee02": "GameCardCardHeaderReadFailure",
        "0x145002": "GameCardShouldTransitFromInitialToNormal",
        "0x145202": "GameCardShouldTransitFromNormalModeToSecure",
        "0x145402": "GameCardShouldTransitFromNormalModeToDebug",
        "0x149402": "GameCardSendFirmwareFailure",
        "0x149a02": "GameCardReceiveCertificateFailure",
        "0x14a002": "GameCardSendSocCertificateFailure",
        "0x14aa02": "GameCardReceiveRandomValueFailure",
        "0x14ac02": "GameCardSendRandomValueFailure",
        "0x14b602": "GameCardReceiveDeviceChallengeFailure",
        "0x14b802": "GameCardRespondDeviceChallengeFailure",
        "0x14ba02": "GameCardSendHostChallengeFailure",
        "0x14bc02": "GameCardReceiveChallengeResponseFailure",
        "0x14be02": "GameCardChallengeAndResponseFailure",
        "0x14d802": "GameCardSplGenerateRandomBytesFailure",
        "0x14de02": "GameCardReadRegisterFailure",
        "0x14e002": "GameCardWriteRegisterFailure",
        "0x14e202": "GameCardEnableCardBusFailure",
        "0x14e402": "GameCardGetCardHeaderFailure",
        "0x14e602": "GameCardAsicStatusError",
        "0x14e802": "GameCardChangeGcModeToSecureFailure",
        "0x14ea02": "GameCardChangeGcModeToDebugFailure",
        "0x14ec02": "GameCardReadRmaInfoFailure",
        "0x150802": "GameCardStateCardSecureModeRequired",
        "0x150a02": "GameCardStateCardDebugModeRequired",
        "0x155602": "GameCardCommandReadId1Failure",
        "0x155802": "GameCardCommandReadId2Failure",
        "0x155a02": "GameCardCommandReadId3Failure",
        "0x155e02": "GameCardCommandReadPageFailure",
        "0x156202": "GameCardCommandWritePageFailure",
        "0x156402": "GameCardCommandRefreshFailure",
        "0x156c02": "GameCardCommandReadCrcFailure",
        "0x156e02": "GameCardCommandEraseFailure",
        "0x157002": "GameCardCommandReadDevParamFailure",
        "0x157202": "GameCardCommandWriteDevParamFailure",
        "0x16b002": "GameCardDebugCardReceivedIdMismatch",
        "0x16b202": "GameCardDebugCardId1Mismatch",
        "0x16b402": "GameCardDebugCardId2Mismatch",
        "0x171402": "GameCardFsCheckHandleInGetStatusFailure",
        "0x172002": "GameCardFsCheckHandleInCreateReadOnlyFailure",
        "0x172202": "GameCardFsCheckHandleInCreateSecureReadOnlyFailure",
        "0x177202": "ResultNotImplemented",
        "0x177602": "ResultAlreadyExists",
        "0x177a02": "ResultOutOfRange",
        "0x190202": "AllocationMemoryFailedInFatFileSystemA",
        "0x190402": "AllocationMemoryFailedInFatFileSystemB",
        "0x190602": "AllocationMemoryFailedInFatFileSystemC",
        "0x190802": "AllocationMemoryFailedInFatFileSystemD",
        "0x190a02": "AllocationMemoryFailedInFatFileSystemE",
        "0x190c02": "AllocationMemoryFailedInFatFileSystemF",
        "0x190e02": "AllocationMemoryFailedInFatFileSystemG",
        "0x191002": "AllocationMemoryFailedInFatFileSystemH",
        "0x195802": "AllocationMemoryFailedInSdCardA",
        "0x195a02": "AllocationMemoryFailedInSdCardB",
        "0x195c02": "AllocationMemoryFailedInSystemSaveDataA",
        "0x195e02": "AllocationMemoryFailedInRomFsFileSystemA",
        "0x196002": "AllocationMemoryFailedInRomFsFileSystemB",
        "0x196202": "AllocationMemoryFailedInRomFsFileSystemC",
        "0x1a3e02": "AllocationMemoryFailedInSdmmcStorageServiceA",
        "0x1a4002": "AllocationMemoryFailedInBuiltInStorageCreatorA",
        "0x1a4a02": "AllocationMemoryFailedInRegisterA",
        "0x21bc02": "IncorrectSaveDataFileSystemMagicCode",
        "0x234202": "InvalidAcidFileSize",
        "0x234402": "InvalidAcidSize",
        "0x234602": "InvalidAcid",
        "0x234802": "AcidVerificationFailed",
        "0x234a02": "InvalidNcaSignature",
        "0x234c02": "NcaHeaderSignature1VerificationFailed",
        "0x234e02": "NcaHeaderSignature2VerificationFailed",
        "0x235002": "NcaFsHeaderHashVerificationFailed",
        "0x235202": "InvalidNcaKeyIndex",
        "0x235602": "InvalidNcaFsHeaderEncryptionType",
        "0x235802": "InvalidNcaPatchInfoIndirectSize",
        "0x235a02": "InvalidNcaPatchInfoAesCtrExSize",
        "0x235c02": "InvalidNcaPatchInfoAesCtrExOffset",
        "0x235e02": "InvalidNcaId",
        "0x236002": "InvalidNcaHeader",
        "0x236202": "InvalidNcaFsHeader",
        "0x236802": "InvalidHierarchicalSha256BlockSize",
        "0x236a02": "InvalidHierarchicalSha256LayerCount",
        "0x236c02": "HierarchicalSha256BaseStorageTooLarge",
        "0x236e02": "HierarchicalSha256HashVerificationFailed",
        "0x244402": "InvalidSha256PartitionHashTarget",
        "0x244602": "Sha256PartitionHashVerificationFailed",
        "0x244802": "PartitionSignatureVerificationFailed",
        "0x244a02": "Sha256PartitionSignatureVerificationFailed",
        "0x244c02": "InvalidPartitionEntryOffset",
        "0x244e02": "InvalidSha256PartitionMetaDataSize",
        "0x249802": "InvalidFatFileNumber",
        "0x249c02": "InvalidFatFormatBisUser",
        "0x249e02": "InvalidFatFormatBisSystem",
        "0x24a002": "InvalidFatFormatBisSafe",
        "0x24a202": "InvalidFatFormatBisCalibration",
        "0x250e02": "AesXtsFileSystemFileHeaderCorruptedOnFileOpen",
        "0x251002": "AesXtsFileSystemFileNoHeaderOnFileOpen",
        "0x280202": "FatFsFormatUnsupportedSize",
        "0x280402": "FatFsFormatInvalidBpb",
        "0x280602": "FatFsFormatInvalidParameter",
        "0x280802": "FatFsFormatIllegalSectorsA",
        "0x280a02": "FatFsFormatIllegalSectorsB",
        "0x280c02": "FatFsFormatIllegalSectorsC",
        "0x280e02": "FatFsFormatIllegalSectorsD",
        "0x296a02": "UnexpectedInMountTableA",
        "0x2ee602": "ResultTooLongPath",
        "0x2ee802": "ResultInvalidCharacter",
        "0x2eea02": "ResultInvalidPathFormat",
        "0x2eec02": "ResultDirectoryUnobtainable",
        "0x2f5a02": "ResultInvalidOffset",
        "0x2f5c02": "ResultInvalidSize",
        "0x2f5e02": "ResultNullptrArgument",
        "0x2f6002": "ResultInvalidAlignment",
        "0x2f6202": "ResultInvalidMountName",
        "0x2f6402": "ResultExtensionSizeTooLarge",
        "0x2f6602": "ResultExtensionSizeInvalid",
        "0x307202": "ResultFileExtensionWithoutOpenModeAllowAppend",
        "0x313a02": "UnsupportedCommitTarget",
        "0x313c02": "UnsupportedSetSizeForNotResizableSubStorage",
        "0x313e02": "UnsupportedSetSizeForResizableSubStorage",
        "0x314002": "UnsupportedSetSizeForMemoryStorage",
        "0x314202": "UnsupportedOperateRangeForMemoryStorage",
        "0x314402": "UnsupportedOperateRangeForFileStorage",
        "0x314602": "UnsupportedOperateRangeForFileHandleStorage",
        "0x314802": "UnsupportedOperateRangeForSwitchStorage",
        "0x314a02": "UnsupportedOperateRangeForStorageServiceObjectAdapter",
        "0x314c02": "UnsupportedWriteForAesCtrCounterExtendedStorage",
        "0x314e02": "UnsupportedSetSizeForAesCtrCounterExtendedStorage",
        "0x315002": "UnsupportedOperateRangeForAesCtrCounterExtendedStorage",
        "0x315202": "UnsupportedWriteForAesCtrStorageExternal",
        "0x315402": "UnsupportedSetSizeForAesCtrStorageExternal",
        "0x315602": "UnsupportedSetSizeForAesCtrStorage",
        "0x315802": "UnsupportedSetSizeForHierarchicalIntegrityVerificationStorage",
        "0x315a02": "UnsupportedOperateRangeForHierarchicalIntegrityVerificationStorage",
        "0x315c02": "UnsupportedSetSizeForIntegrityVerificationStorage",
        "0x315e02": "UnsupportedOperateRangeForWritableIntegrityVerificationStorage",
        "0x316002": "UnsupportedOperateRangeForIntegrityVerificationStorage",
        "0x316202": "UnsupportedSetSizeForBlockCacheBufferedStorage",
        "0x316402": "UnsupportedOperateRangeForWritableBlockCacheBufferedStorage",
        "0x316602": "UnsupportedOperateRangeForBlockCacheBufferedStorage",
        "0x316802": "UnsupportedWriteForIndirectStorage",
        "0x316a02": "UnsupportedSetSizeForIndirectStorage",
        "0x316c02": "UnsupportedOperateRangeForIndirectStorage",
        "0x316e02": "UnsupportedWriteForZeroStorage",
        "0x317002": "UnsupportedSetSizeForZeroStorage",
        "0x317202": "UnsupportedSetSizeForHierarchicalSha256Storage",
        "0x317402": "UnsupportedWriteForReadOnlyBlockCacheStorage",
        "0x317602": "UnsupportedSetSizeForReadOnlyBlockCacheStorage",
        "0x317802": "UnsupportedSetSizeForIntegrityRomFsStorage",
        "0x317a02": "UnsupportedSetSizeForDuplexStorage",
        "0x317c02": "UnsupportedOperateRangeForDuplexStorage",
        "0x317e02": "UnsupportedSetSizeForHierarchicalDuplexStorage",
        "0x318002": "UnsupportedGetSizeForRemapStorage",
        "0x318202": "UnsupportedSetSizeForRemapStorage",
        "0x318402": "UnsupportedOperateRangeForRemapStorage",
        "0x318602": "UnsupportedSetSizeForIntegritySaveDataStorage",
        "0x318802": "UnsupportedOperateRangeForIntegritySaveDataStorage",
        "0x318a02": "UnsupportedSetSizeForJournalIntegritySaveDataStorage",
        "0x318c02": "UnsupportedOperateRangeForJournalIntegritySaveDataStorage",
        "0x318e02": "UnsupportedGetSizeForJournalStorage",
        "0x319002": "UnsupportedSetSizeForJournalStorage",
        "0x319202": "UnsupportedOperateRangeForJournalStorage",
        "0x319402": "UnsupportedSetSizeForUnionStorage",
        "0x319602": "UnsupportedSetSizeForAllocationTableStorage",
        "0x319802": "UnsupportedReadForWriteOnlyGameCardStorage",
        "0x319a02": "UnsupportedSetSizeForWriteOnlyGameCardStorage",
        "0x319c02": "UnsupportedWriteForReadOnlyGameCardStorage",
        "0x319e02": "UnsupportedSetSizeForReadOnlyGameCardStorage",
        "0x31a002": "UnsupportedOperateRangeForReadOnlyGameCardStorage",
        "0x31a202": "UnsupportedSetSizeForSdmmcStorage",
        "0x31a402": "UnsupportedOperateRangeForSdmmcStorage",
        "0x31a602": "UnsupportedOperateRangeForFatFile",
        "0x31a802": "UnsupportedOperateRangeForStorageFile",
        "0x31aa02": "UnsupportedSetSizeForInternalStorageConcatenationFile",
        "0x31ac02": "UnsupportedOperateRangeForInternalStorageConcaten",
        "0x31ae02": "UnsupportedQueryEntryForConcatenationFileSystem",
        "0x31b002": "UnsupportedOperateRangeForConcatenationFile",
        "0x31b202": "UnsupportedSetSizeForZeroBitmapFile",
        "0x31b402": "UnsupportedOperateRangeForFileServiceObjectAdapter",
        "0x31b602": "UnsupportedOperateRangeForAesXtsFile",
        "0x31b802": "UnsupportedWriteForRomFsFileSystem",
        "0x31ba02": "UnsupportedCommitProvisionallyForRomFsFileSystem",
        "0x31bc02": "UnsupportedGetTotalSpaceSizeForRomFsFileSystem",
        "0x31be02": "UnsupportedWriteForRomFsFile",
        "0x31c002": "UnsupportedOperateRangeForRomFsFile",
        "0x31c202": "UnsupportedWriteForReadOnlyFileSystem",
        "0x31c402": "UnsupportedCommitProvisionallyForReadOnlyFileSystem",
        "0x31c602": "UnsupportedGetTotalSpaceSizeForReadOnlyFileSystem",
        "0x31c802": "UnsupportedWriteForReadOnlyFile",
        "0x31ca02": "UnsupportedOperateRangeForReadOnlyFile",
        "0x31cc02": "UnsupportedWriteForPartitionFileSystem",
        "0x31ce02": "UnsupportedCommitProvisionallyForPartitionFileSystem",
        "0x31d002": "UnsupportedWriteForPartitionFile",
        "0x31d202": "UnsupportedOperateRangeForPartitionFile",
        "0x31d402": "UnsupportedOperateRangeForTmFileSystemFile",
        "0x31d602": "UnsupportedWriteForSaveDataInternalStorageFileSystem",
        "0x31dc02": "UnsupportedCommitProvisionallyForApplicationTemporaryFileSystem",
        "0x31de02": "UnsupportedCommitProvisionallyForSaveDataFileSystem",
        "0x31e002": "UnsupportedCommitProvisionallyForDirectorySaveDataFileSystem",
        "0x31e202": "UnsupportedWriteForZeroBitmapHashStorageFile",
        "0x31e402": "UnsupportedSetSizeForZeroBitmapHashStorageFile",
        "0x326602": "ResultNcaExternalKeyUnregisteredDeprecated",
        "0x326e02": "ResultFileNotClosed",
        "0x327002": "ResultDirectoryNotClosed",
        "0x327202": "ResultWriteModeFileNotClosed",
        "0x327402": "ResultAllocatorAlreadyRegistered",
        "0x327602": "ResultDefaultAllocatorAlreadyUsed",
        "0x327a02": "ResultAllocatorAlignmentViolation",
        "0x328202": "ResultUserNotExist",
        "0x339402": "FileNotFound",
        "0x339602": "DirectoryNotFound",
        "0x346402": "MappingTableFull",
        "0x346a02": "OpenCountLimit",
        "0x346c02": "MultiCommitFileSystemLimit",
        "0x353602": "MapFull",
        "0x35f202": "NotMounted",
        "0x3dbc02": "DbmKeyNotFound",
        "0x3dbe02": "DbmFileNotFound",
        "0x3dc002": "DbmDirectoryNotFound",
        "0x3dc402": "DbmAlreadyExists",
        "0x3dc602": "DbmKeyFull",
        "0x3dc802": "DbmDirectoryEntryFull",
        "0x3dca02": "DbmFileEntryFull",
        "0x3dd402": "DbmInvalidOperation",
        "0x203": "ResultNoPermission",
        "0x403": "ResultAccessViolation",
        "0x603": "ResultBadRequest",
        "0x803": "ResultBusy",
        "0xa03": "ResultDeadlock",
        "0xc03": "ResultInvalidAddress",
        "0xe03": "ResultInvalidParameter",
        "0x1003": "ResultOutOfMemory",
        "0x1203": "ResultOutOfResource",
        "0x3ea03": "InvalidHandle",
        "0x3ec03": "InvalidCurrentMemoryState",
        "0x3ee03": "InvalidTransferMemoryState",
        "0x3f003": "InvalidTransferMemorySize",
        "0x7fe03": "ResultInternalError",
        "0xa05": "ContentNotFound",
        "0xe05": "ContentMetaNotFound",
        "0x1805": "UnknownStorage",
        "0xdc05": "InvalidContentMetaDatabase",
        "0x17c05": "WriteToReadOnlyContentStorage",
        "0x806": "InvalidMemoryState",
        "0x1006": "InvalidHandle",
        "0x408": "ProgramNotFound",
        "0x608": "DataNotFound",
        "0x808": "UnknownResolver",
        "0xa08": "ApplicationNotFound",
        "0xc08": "HtmlDocumentNotFound",
        "0xe08": "AddOnContentNotFound",
        "0x1008": "ControlNotFound",
        "0x1208": "LegalInformationNotFound",
        "0x1408": "DebugProgramNotFound",
        "0x209": "TooLongArgument",
        "0x409": "TooManyArguments",
        "0x609": "TooLargeMeta",
        "0x809": "InvalidMeta",
        "0xa09": "InvalidNso",
        "0xc09": "InvalidPath",
        "0xe09": "TooManyProcesses",
        "0x1009": "NotPinned",
        "0x1209": "InvalidProgramId",
        "0x1409": "InvalidVersion",
        "0x6609": "InsufficientAddressSpace",
        "0x6809": "InvalidNro",
        "0x6a09": "InvalidNrr",
        "0x6c09": "InvalidSignature",
        "0x6e09": "InsufficientNroRegistrations",
        "0x7009": "InsufficientNrrRegistrations",
        "0x7209": "NroAlreadyLoaded",
        "0xa209": "InvalidAddress",
        "0xa409": "InvalidSize",
        "0xa809": "NotLoaded",
        "0xaa09": "NotRegistered",
        "0xae09": "InvalidProcess",
        "0xc809": "UnknownCapability",
        "0xce09": "InvalidCapabilityKernelFlags",
        "0xd009": "InvalidCapabilitySyscallMask",
        "0xd409": "InvalidCapabilityMapRange",
        "0xd609": "InvalidCapabilityMapPage",
        "0xde09": "InvalidCapabilityInterruptPair",
        "0xe209": "InvalidCapabilityApplicationType",
        "0xe409": "InvalidCapabilityKernelVersion",
        "0xe609": "InvalidCapabilityHandleTable",
        "0xe809": "InvalidCapabilityDebugFlags",
        "0x1940a": "InvalidCmifHeaderSize",
        "0x1a60a": "InvalidCmifInHeader",
        "0x1a80a": "InvalidCmifOutHeader",
        "0x1ba0a": "UnknownMethodId",
        "0x1d60a": "InvalidInObjectCount",
        "0x1d80a": "InvalidOutObjectCount",
        "0x25a0a": "OutOfDomainEntry",
        "0x20b": "NotSupported",
        "0xcc0b": "OutOfSessionMemory",
        "0x11a0b": "InsufficientPointerTransferBuffer",
        "0x1900b": "OutOfDomains",
        "0x25a0b": "SessionClosed",
        "0x3240b": "InvalidRequestSize",
        "0x3260b": "UnknownCommandType",
        "0x3d60b": "TargetNotDomain",
        "0x20f": "ProcessNotFound",
        "0x60f": "NotTerminated",
        "0xa0f": "ApplicationRunning",
        "0x410": "Title-id not found.",
        "0xf010": "Sysupdate not required.",
        "0x1f610": "Unexpected StorageId.",
        "0x2a810": "IsAnyInternetRequestAccepted with the output from GetClientId returned false.",
        "0x64210": "SystemDeliveryInfo system_delivery_protocol_version is less than the system-setting.",
        "0x64410": "SystemDeliveryInfo system_delivery_protocol_version is larger than the system-setting.",
        "0x6f810": "Unknown state ref-count is zero.",
        "0x74610": "Invalid SystemDeliveryInfo HMAC / invalid Meta Id.",
        "0x215": "OutOfProcesses",
        "0x415": "InvalidClient",
        "0x615": "OutOfSessions",
        "0x815": "AlreadyRegistered",
        "0xa15": "OutOfServices",
        "0xc15": "InvalidServiceName",
        "0xe15": "NotRegistered",
        "0x1015": "NotAllowed",
        "0x1215": "TooLargeAccessControl",
        "0x416": "ResultOutOfAddressSpace",
        "0x616": "ResultNroAlreadyLoaded",
        "0x816": "ResultInvalidNroImage",
        "0xc16": "ResultInvalidNrrImage",
        "0x1016": "ResultMaxRegistration",
        "0x1216": "ResultNotAuthorized",
        "0x80216": "InvalidAddress",
        "0x80416": "InvalidSize",
        "0x80816": "NotLoaded",
        "0x80a16": "NotRegistered",
        "0x80c16": "InvalidSession",
        "0x80e16": "InvalidProcess",
        "0x21a": "SecureMonitorNotImplemented",
        "0x41a": "SecureMonitorInvalidArgument",
        "0x61a": "SecureMonitorBusy",
        "0x81a": "SecureMonitorNoAsyncOperation",
        "0xa1a": "SecureMonitorInvalidAsyncOperation",
        "0xc1a": "SecureMonitorNotPermitted",
        "0xc81a": "InvalidSize",
        "0xca1a": "UnknownSecureMonitorError",
        "0xcc1a": "DecryptionFailed",
        "0xd01a": "OutOfKeySlots",
        "0xd21a": "InvalidKeySlot",
        "0xd41a": "BootReasonAlreadySet",
        "0xd61a": "BootReasonNotSet",
        "0xd81a": "InvalidArgument",
        "0x1423": "Invalid command ID received by tipc processor.",
        "0x1e23": "Invalid message format received by tipc processor.",
        "0xc823": "Tipc request was deferred for future processing (internal to the processor, never returned externally).",
        "0xca23": "Tipc object was closed (via close command 0xF, internal, never returned externally).",
        "0x19269": "SettingsNameNull",
        "0x19469": "SettingsItemKeyNull",
        "0x19669": "SettingsItemValueNull",
        "0x19a69": "SettingsItemValueBufferNull",
        "0x1a069": "Null setting value size buffer.",
        "0x1a269": "Null debug mode flag buffer.",
        "0x1ba69": "SettingsNameEmpty",
        "0x1bc69": "SettingsItemKeyEmpty",
        "0x1e269": "SettingsNameTooLong",
        "0x1e469": "SettingsItemKeyTooLong",
        "0x20a69": "SettingsNameInvalidFormat",
        "0x20c69": "SettingsItemKeyInvalidFormat",
        "0x4da69": "Null language code buffer.",
        "0x4e269": "Language out of valid range.",
        "0x4ee69": "Null network settings buffer.",
        "0x4f069": "Null network settings output count buffer.",
        "0x50269": "Null backlight settings buffer.",
        "0x51669": "Null Bluetooth device setting buffer.",
        "0x51869": "Null Bluetooth device setting output count buffer.",
        "0x51a69": "Null Bluetooth enable flag buffer.",
        "0x51c69": "Null Bluetooth AFH enable flag buffer.",
        "0x51e69": "Null Bluetooth boost enable flag buffer.",
        "0x52069": "Null BLE pairing settings buffer.",
        "0x52269": "Null BLE pairing settings entry count buffer.",
        "0x52a69": "Null external steady clock source ID buffer.",
        "0x52c69": "Null user system clock context buffer.",
        "0x52e69": "Null network system clock context buffer.",
        "0x53069": "Null user system clock automatic correction enabled flag buffer.",
        "0x53269": "Null shutdown RTC value buffer.",
        "0x53469": "Null external steady clock internal offset buffer.",
        "0x53e69": "Null account settings buffer.",
        "0x55269": "Null audio volume buffer.",
        "0x55669": "Null ForceMuteOnHeadphoneRemoved buffer.",
        "0x55869": "Null headphone volume warning count buffer.",
        "0x55e69": "Invalid audio output mode.",
        "0x56069": "Null headphone volume update flag buffer.",
        "0x56669": "Null console information upload flag buffer.",
        "0x57a69": "Null automatic application download flag buffer.",
        "0x57c69": "Null notification settings buffer.",
        "0x57e69": "Null account notification settings entry count buffer.",
        "0x58069": "Null account notification settings buffer.",
        "0x58e69": "Null vibration master volume buffer.",
        "0x59069": "Null NX controller settings buffer.",
        "0x59269": "Null NX controller settings entry count buffer.",
        "0x59469": "Null USB full key enable flag buffer.",
        "0x5a269": "Null TV settings buffer.",
        "0x5a469": "Null EDID buffer.",
        "0x5b669": "Null data deletion settings buffer.",
        "0x5ca69": "Null initial system applet program ID buffer.",
        "0x5cc69": "Null overlay disp program ID buffer.",
        "0x5ce69": "Null IsInRepairProcess buffer.",
        "0x5d069": "Null RequiresRunRepairTimeReviser buffer.",
        "0x5de69": "Null device timezone location name buffer.",
        "0x5f269": "Null primary album storage buffer.",
        "0x60669": "Null USB 3.0 enable flag buffer.",
        "0x60869": "Null USB Type-C power source circuit version buffer.",
        "0x61a69": "Null battery lot buffer.",
        "0x62e69": "Null serial number buffer.",
        "0x64269": "Null lock screen flag buffer.",
        "0x64669": "Null color set ID buffer.",
        "0x64869": "Null quest flag buffer.",
        "0x64a69": "Null wireless certification file size buffer.",
        "0x64c69": "Null wireless certification file buffer.",
        "0x64e69": "Null initial launch settings buffer.",
        "0x65069": "Null device nickname buffer.",
        "0x65269": "Null battery percentage flag buffer.",
        "0x65469": "Null applet launch flags buffer.",
        "0x7e869": "Null wireless LAN enable flag buffer.",
        "0x7fa69": "Null product model buffer.",
        "0x80e69": "Null NFC enable flag buffer.",
        "0x82269": "Null ECI device certificate buffer.",
        "0x82469": "Null E-Ticket device certificate buffer.",
        "0x83669": "Null sleep settings buffer.",
        "0x84a69": "Null EULA version buffer.",
        "0x84c69": "Null EULA version entry count buffer.",
        "0x85e69": "Null LDN channel buffer.",
        "0x87269": "Null SSL key buffer.",
        "0x87469": "Null SSL certificate buffer.",
        "0x88669": "Null telemetry flags buffer.",
        "0x89a69": "Null Gamecard key buffer.",
        "0x89c69": "Null Gamecard certificate buffer.",
        "0x8ae69": "Null PTM battery lot buffer.",
        "0x8b069": "Null PTM fuel gauge parameter buffer.",
        "0x8c269": "Null ECI device key buffer.",
        "0x8c469": "Null E-Ticket device key buffer.",
        "0x8d669": "Null speaker parameter buffer.",
        "0x8ea69": "Null firmware version buffer.",
        "0x8ec69": "Null firmware version digest buffer.",
        "0x8ee69": "Null rebootless system update version buffer.",
        "0x8fe69": "Null Mii author ID buffer.",
        "0x91269": "Null fatal flags buffer.",
        "0x92669": "Null auto update enable flag buffer.",
        "0x93a69": "Null external RTC reset flag buffer.",
        "0x94e69": "Null push notification activity mode buffer.",
        "0x96269": "Null service discovery control setting buffer.",
        "0x97669": "Null error report share permission buffer.",
        "0x98a69": "Null LCD vendor ID buffer.",
        "0x99e69": "Null console SixAxis sensor acceleration bias buffer.",
        "0x9a069": "Null console SixAxis sensor angular velocity bias buffer.",
        "0x9a269": "Null console SixAxis sensor acceleration gain buffer.",
        "0x9a469": "Null console SixAxis sensor angular velocity gain buffer.",
        "0x9a669": "Null console SixAxis sensor angular velocity time bias buffer.",
        "0x9a869": "Null console SixAxis sensor angular acceleration buffer.",
        "0x9b269": "Null keyboard layout buffer.",
        "0x9ba69": "Invalid keyboard layout.",
        "0x9c669": "Null web inspector flag buffer.",
        "0x9c869": "Null allowed SSL hosts buffer.",
        "0x9ca69": "Null allowed SSL hosts entry count buffer.",
        "0x9cc69": "Null host FS mount point buffer.",
        "0x9ee69": "Null Amiibo key buffer.",
        "0x9f069": "Null Amiibo ECQV certificate buffer.",
        "0x9f269": "Null Amiibo ECDSA certificate buffer.",
        "0x9f469": "Null Amiibo ECQV BLS key buffer.",
        "0x9f669": "Null Amiibo ECQV BLS certificate buffer.",
        "0x9f869": "Null Amiibo ECQV BLS root certificate buffer.",
        "0x272": "ResultOperationFailed",
        "0xc72": "ResultNotSupported",
        "0x74": "ResultNotInitialized",
        "0x274": "ResultNoCapability",
        "0xcc74": "OffsetInvalid",
        "0xce74": "UninitializedClock",
        "0x19074": "ResultNotComparable",
        "0x19274": "ResultOverflowed",
        "0x64274": "ResultOutOfMemory",
        "0x70a74": "InvalidPointer",
        "0x70c74": "OutOfRange",
        "0x70e74": "InvalidTimeZoneBinary",
        "0x7ba74": "NotFound",
        "0x7bc74": "NotImplemented",
        "0xc79": "ResultInternetRequestNotAccepted",
        "0x27a": "ResultInvalidArgument",
        "0x47a": "ResultNotFound",
        "0x67a": "ResultLocked",
        "0x87a": "ResultAlreadyMounted",
        "0xa7a": "ResultNotMounted",
        "0xc7a": "ResultAlreadyOpened",
        "0xe7a": "ResultNotOpened",
        "0x107a": "ResultInternetRequestNotAccepted",
        "0xa07a": "ResultPassphraseNotSaved",
        "0xa27a": "ResultDataVerificationFailed",
        "0xb47a": "ResultNotPermitted",
        "0xc47a": "ResultInvalidOperation",
        "0x167b": "ResultErrorLower",
        "0x1a7b": "ResultInternalLogicError",
        "0xcc7b": "ResultInsufficientMemory",
        "0xe87b": "ResultInvalidSocketDescriptor",
        "0x1027b": "ResultInvalidCrlFormat",
        "0x1987b": "ResultIoWouldBlock",
        "0x19a7b": "ResultIoTimeout",
        "0x19c7b": "ResultIoAborted",
        "0x1a07b": "ResultNoConnection",
        "0x1a27b": "ResultConnectionReset",
        "0x1a47b": "ResultConnectionAborted",
        "0x1a67b": "ResultSocketShutdown",
        "0x1a87b": "ResultNetworkDown",
        "0x1ae7b": "ResultClientPkiAlreadyRegistered",
        "0x1b47b": "ResultMaxServerPkiRegistered",
        "0x25a7b": "ResultSslErrorInvalidCertDomain",
        "0x25c7b": "ResultSslErrorNoCertificate",
        "0x25e7b": "ResultSslErrorExpiredCertificate",
        "0x2607b": "ResultSslErrorRevokedCertificate",
        "0x2627b": "ResultSslErrorUnsupportedCertificate",
        "0x2647b": "ResultSslErrorUnknownCertificate",
        "0x2667b": "ResultSslErrorBadCertificate",
        "0x2687b": "ResultSslErrorUnkownCa",
        "0x26a7b": "ResultSslErrorAccessDenied",
        "0x26c7b": "ResultSslErrorReceivedUnkownData",
        "0x26e7b": "ResultSslErrorReceivedMalformedData",
        "0x2707b": "ResultSslErrorReceivedUnexpectedHandshakeData",
        "0x2727b": "ResultSslErrorReceivedUnexpectedRecordData",
        "0x2747b": "ResultSslErrorReceivedTooLongRecord",
        "0x2767b": "ResultSslErrorUnexpectedHelloVerifyRequest",
        "0x2787b": "ResultSslErrorUnexpectedCertificateStatusResponse",
        "0x27a7b": "ResultSslErrorInconsistentSignAlgorithm",
        "0x27c7b": "ResultSslErrorInsufficientSecurity",
        "0x27e7b": "ResultSslErrorDecryptionWithInvalidMac",
        "0x2827b": "ResultSslErrorDigestCalculationFailed",
        "0x2847b": "ResultSslErrorMacCalculationFailed",
        "0x2887b": "ResultSslErrorNoExtendedField",
        "0x28a7b": "ResultSslErrorUntrustedOid",
        "0x2947b": "ResultSslErrorDecompressionFailed",
        "0xbba7b": "ResultSslAlertCloseNotify",
        "0xbbc7b": "ResultSslAlertUnexpectedMessage",
        "0xbbe7b": "ResultSslAlertBadRecordMac",
        "0xbc07b": "ResultSslAlertDecriptionFailed",
        "0xbc27b": "ResultSslAlertRecordOverfrlow",
        "0xbc47b": "ResultSslAlertDecompressionFailure",
        "0xbc67b": "ResultSslAlertHandshakeFailure",
        "0xbca7b": "ResultSslAlertBadCertificate",
        "0xbcc7b": "ResultSslAlertUnsupportedCertificate",
        "0xbce7b": "ResultSslAlertCertificateRevoked",
        "0xbd07b": "ResultSslAlertCertificateExpired",
        "0xbd27b": "ResultSslAlertCertificateUnkown",
        "0xbd47b": "ResultSslAlertIllegalParameter",
        "0xbd67b": "ResultSslAlertUnknownCa",
        "0xbd87b": "ResultSslAlertAccessDenied",
        "0xbda7b": "ResultSslAlertDecodeError",
        "0xbdc7b": "ResultSslAlertDecryptError",
        "0xbde7b": "ResultSslAlertExportRestriction",
        "0xbe07b": "ResultSslAlertProtocolVersion",
        "0xbe27b": "ResultSslAlertInsufficientSecurity",
        "0xbe47b": "ResultSslAlertInternalError",
        "0xbe67b": "ResultSslAlertInappropriateFallback",
        "0xbe87b": "ResultSslAlertUserCancelled",
        "0xbea7b": "ResultSslAlertNoRenegotiation",
        "0xbec7b": "ResultSslAlertUnsupportedExtention",
        "0xbee7b": "ResultSslAlertCertificateUnobtainable",
        "0xbf07b": "ResultSslAlertUnrecognizedName",
        "0xbf27b": "ResultSslAlertBadCertificateStatusResponse",
        "0xbf47b": "ResultSslAlertBadCertificateHashValue",
        "0x27127b": "Converted from NSS SSL error -12155 (SSL_ERROR_RX_SHORT_DTLS_READ)",
        "0x271e7b": "Out-of-bounds error during error conversion",
        "0x7c": "ResultCancelled",
        "0x27c": "ResultCancelledByUser",
        "0x287c": "ResultInvalidUserId",
        "0x2a7c": "ResultInvalidUserPosition",
        "0x2c7c": "ResultInvalidApplication",
        "0x3c7c": "ResultNullptr",
        "0x3e7c": "ResultInsufficientBuffer",
        "0x407c": "ResultInvalidArrayLength",
        "0x427c": "ResultInvalidStringFormat",
        "0x447c": "ResultValueOutOfRange",
        "0x507c": "ResultInvalidObjectAccess",
        "0x527c": "ResultInvalidProtocolAccess",
        "0x767c": "ResultInternetConnectionRequestNotAccepted",
        "0xc87c": "ResultUserNotExist",
        "0xca7c": "ResultUserAlreadyOpened",
        "0xcc7c": "ResultUserAlreadyClosed",
        "0xce7c": "ResultUserReferred",
        "0xd07c": "ResultUserUnqualified",
        "0xd27c": "ResultNeverBeenQualified",
        "0x1907c": "ResultNetworkServiceAccountRegistrationRequired",
        "0x1a47c": "ResultNetworkServiceAccountCredentialBroken",
        "0x1a67c": "ResultNetworkServiceAccountUnmanaged",
        "0x1a87c": "ResultNetworkServiceAccountBanned",
        "0x1cc7c": "ResultNintendoAccountLinkageBroken",
        "0x1e07c": "ResultNintendoAccountStateOtherButInteractionRequired",
        "0x1e27c": "ResultNintendoAccountStateDeleted",
        "0x1e47c": "ResultNintendoAccountStateBanned",
        "0x1e67c": "ResultNintendoAccountStateSuspended",
        "0x1e87c": "ResultNintendoAccountStateWithdrawn",
        "0x1ea7c": "ResultNintendoAccountStateTermsAgreementRequired",
        "0x2067c": "ResultNintendoAccountStateReauthorizationRequired",
        "0x17707c": "ResultUnacceptableSystemVersion",
        "0x17727c": "ResultUnacceptableApplicationVersion",
        "0x1f4e7c": "Account Permanent Ban",
        "0x23387c": "Account Permanent Ban",
        "0x234a7c": "Account Ban",
        "0x24027c": "Service Discontinued",
        "0x27107c": "ResultInvalidParams",
        "0x27127c": "ResultInvalidRequest",
        "0x27147c": "ResultInvalidDeviceAccount",
        "0x27167c": "ResultInvalidNdasAppAuthnToken",
        "0x27187c": "ResultInvalidIdp",
        "0x271a7c": "ResultInvalidIdpAccount",
        "0x271c7c": "ResultLinkedUserNotFound",
        "0x271e7c": "ResultInvalidFriendCodeFormat",
        "0x27207c": "ResultUserLinkNotExist",
        "0x27d87c": "ResultInvalidRawContent",
        "0x27da7c": "ResultInsufficientScope",
        "0x27dc7c": "ResultForbidden",
        "0x27de7c": "ResultUnavailableDeviceAccount",
        "0x27e07c": "ResultResourceIsNotFound",
        "0x27e27c": "ResultMethodNotAllowed",
        "0x27e47c": "ResultNotAcceptableLanguage",
        "0x27e67c": "ResultResourceAlreadyExists",
        "0x27e87c": "ResultUserLinkAlreadyExists",
        "0x27ea7c": "ResultPreconditionFailed",
        "0x27ec7c": "ResultFriendCodeUnregenerableState",
        "0x27ee7c": "ResultBannedUser",
        "0x27f07c": "ResultDeletedUser",
        "0x27f27c": "ResultMembershipRequired",
        "0x27f47c": "ResultBannedUserByApplication",
        "0x28a07c": "ResultInternalServerError",
        "0x28b47c": "ResultCouldNotConfirmMembership",
        "0x29027c": "ResultUnderMaintenance",
        "0x27e": "ResultInvalid",
        "0x87e": "ResultNotFound",
        "0xce7e": "Invalid database signature value (should be 'NFDB')",
        "0xd27e": "Invalid database entry count",
        "0x1987e": "ResultDevelopmentOnly",
        "0x480": "IStorage not available",
        "0x680": "No messages",
        "0x4680": "Error while launching applet",
        "0x4a80": "Title-ID not found. Caused by code 0x410 when applet launch fails",
        "0x3e880": "Invalid input",
        "0x3ec80": "IStorage has already been opened by another accessor",
        "0x3ee80": "IStorage Read/Write out-of-bounds",
        "0x3f480": "Invalid parameters",
        "0x3fe80": "IStorage opened as wrong type (data opened as transfermem, transfermem opened as data)",
        "0x40080": "Unbalanced fatal section leave (returned when executing LeaveFatalSection without a preceding EnterFatalSection call)",
        "0x40c80": "Null object",
        "0x4b080": "Failed to allocate memory for IStorage",
        "0x59080": "Thread stack pool exhausted (out of memory)",
        "0x79c80": "DebugMode not enabled",
        "0x7a880": "am.debug!dev_function setting needs to be set / DebugMode not enabled",
        "0x7cc80": "Not implemented",
        "0xcc81": "Transmission not agreed",
        "0xd281": "Network unavailable",
        "0x7da81": "HTTP error: Couldnt resolve proxy",
        "0x7dc81": "HTTP error: Couldnt resolve host",
        "0x7de81": "HTTP error: Couldnt connect",
        "0x7fe81": "HTTP error: Write error",
        "0x80481": "HTTP error: Read error",
        "0x80681": "HTTP error: Out of memory",
        "0x80881": "HTTP error: Operation timedout",
        "0x81681": "HTTP error: SSL connect error",
        "0x83681": "HTTP error: Peer failed verification",
        "0x83881": "HTTP error: Got nothing",
        "0x83e81": "HTTP error: Send error",
        "0x84081": "HTTP error: Recv error",
        "0x84481": "HTTP error: SSL cert problem",
        "0x84681": "HTTP error: SSL cipher",
        "0x84881": "HTTP error: SSL CA cert",
        "0x12c081": "Server error: Status 400",
        "0x12c281": "Server error: Status 401",
        "0x12c681": "Server error: Status 403",
        "0x138881": "Server error: Status 500",
        "0x138e81": "Server error: Status 503",
        "0x139081": "Server error: Status 504",
        "0xa83": "Unrecognized applet ID",
        "0x485": "Invalid DVFS table ID",
        "0x685": "DVFS table ID for debug only",
        "0x885": "Invalid parameter",
        "0x1489": "Already initialized",
        "0x3c89": "Task not found",
        "0x5089": "Memory allocation failed / bad input",
        "0x29489": "ContentMetaType doesnt match SystemUpdate",
        "0x271289": "One of the following socket errors occurred: ENETDOWN, ECONNRESET, EHOSTDOWN, EHOSTUNREACH, or EPIPE. Also occurs when the received size doesnt match the expected size (recvfrom() ret with meta_size data receiving)",
        "0x272489": "Socket was shutdown() due to the async operation being cancelled",
        "0x273889": "Too many internal output entries with nim cmd42, system is Internet-connected, or an unrecognized socket error occured",
        "0x27d889": "Connection timeout",
        "0x2a4489": "Invalid ID",
        "0x2a5889": "Invalid magicnum. Can also be caused by the connection being closed by the peer, since non-negative return values from recv() are ignored in this case",
        "0x2a6c89": "Invalid data_size",
        "0x2a8089": "The input ContentMetaKey doesnt match the ContentMetaKey in state",
        "0x2a9489": "Invalid meta_size",
        "0x36b289": "HTTP invalid response code (>=600)",
        "0x36b489": "HTTP invalid client response code (4xx)",
        "0x36b689": "HTTP invalid server response code (5xx)",
        "0x36b889": "HTTP invalid redirect response code (3xx)",
        "0x3cf089": "Unknown/invalid libcurl error",
        "0x68a": "NotInitialized",
        "0x28c": "ResultInterfaceInvalid",
        "0xa8c": "ResultMemAllocFailure",
        "0x108c": "ResultInternalStateError",
        "0x1e8c": "ResultEndpointStateInvalid",
        "0x2a8c": "ResultUrbLimitExceeded",
        "0x608c": "ResultInvalidDeviceState",
        "0x628c": "ResultUsbEndpointAlreadyOpen",
        "0x648c": "ResultInvalidAlternateSetting",
        "0x668c": "USB data-transfer in progress",
        "0x868c": "ResultPlatformInvalid",
        "0xc88c": "ResultInvalidArgument",
        "0xca8c": "ResultInvalidOffset",
        "0xcc8c": "ResultInvalidSize",
        "0xce8c": "ResultInvalidAlignment",
        "0xd48c": "Invalid descriptor",
        "0x1928c": "ResultOperationDenied",
        "0x1be8e": "IsAnyInternetRequestAccepted with the output from GetClientId returned false",
        "0x290": "Exited Abnormally (ExitReason == Abormal)",
        "0x690": "Canceled (ExitReason == Canceled)",
        "0x890": "Rejected",
        "0xa90": "Exited Unexpectedly (ExitReason == Unexpected)",
        "0x293": "NotInitialized",
        "0x493": "AlreadyInitialized",
        "0x693": "OutOfArraySpace",
        "0x893": "OutOfFieldSpace",
        "0xa93": "OutOfMemory",
        "0xc93": "NotSupported",
        "0xe93": "InvalidArgument",
        "0x1093": "NotFound",
        "0x1293": "FieldCategoryMismatch",
        "0x1493": "FieldTypeMismatch",
        "0x1693": "AlreadyExists",
        "0x1893": "CorruptJournal",
        "0x1a93": "CategoryNotFound",
        "0x1c93": "RequiredContextMissing",
        "0x1e93": "RequiredFieldMissing",
        "0x2093": "FormatterError",
        "0x2293": "InvalidPowerState",
        "0x2493": "ArrayFieldTooLarge",
        "0x2693": "AlreadyOwned",
        "0x299": "ResultNotFound",
        "0x499": "ResultOperationFailed",
        "0x699": "ResultInvalidSampleRate",
        "0x899": "ResultInsufficientBuffer",
        "0x1099": "Too many buffers are still unreleased",
        "0x1499": "ResultInvalidChannelCount",
        "0x40299": "ResultNotSupported",
        "0xc0099": "Invalid handle",
        "0xc0899": "Audio output was already started",
        "0x3c9d": "Address is NULL",
        "0x3e9d": "PID is NULL",
        "0x549d": "Already bound",
        "0xcc9d": "Invalid PID",
        "0x49e": "BootImagePackageNotFound",
        "0x69e": "InvalidBootImagePackage",
        "0x89e": "TooSmallWorkBuffer",
        "0xa9e": "NotAlignedWorkBuffer",
        "0xc9e": "NeedsRepairBootImages",
        "0x29f": "ResultCanceled",
        "0x2a2": "ApplicationAborted",
        "0x4a2": "SystemModuleAborted",
        "0x6a2": "ApplicationExitTimeout",
        "0x8a2": "ForcedShutdownDetected",
        "0xc8a2": "UnacceptableApplicationVersion",
        "0xcaa2": "UnacceptableAddOnContentVersion",
        "0xaa3": "InRepairWithoutVolHeld",
        "0xca3": "InRepairWithoutTimeReviserCartridge",
        "0x70a4": "ResultInternetRequestNotAccepted",
        "0xa8": "UndefinedInstruction",
        "0x2a8": "InstructionAbort",
        "0x4a8": "DataAbort",
        "0x6a8": "AlignmentFault",
        "0x8a8": "DebuggerAttached",
        "0xaa8": "BreakPoint",
        "0xca8": "UserBreak",
        "0xea8": "DebuggerBreak",
        "0x10a8": "UndefinedSystemCall",
        "0x12a8": "MemorySystemError",
        "0xc6a8": "IncompleteReport",
        "0x4af": "Bad version returned from calling the 'nnjitpluginGetVersion' symbol",
        "0xcaaf": "Input NRO/NRR are too large for the storage buffer",
        "0x4b0af": "Symbol funcptr used by this cmd is not initialized (Control/GenerateCode)",
        "0x4b2af": "DllPlugin Not initialized, or plugin NRO has already been loaded",
        "0x4b4af": "An error was returned from calling the symbol funcptr with the Control cmd",
        "0xc8b2": "Invalid user ID",
        "0xcab2": "User does not exist",
        "0x12cb2": "Service unavailable",
        "0x190b2": "File storage failure",
        "0xab4": "Invalid event ID",
        "0x7d0b5": "Invalid ELicense ID",
        "0x1f4eb5": "Device authentication error: System update required",
        "0x1f50b5": "Device authentication error: Permanant Ban",
        "0x1f52b5": "Device authentication error: Internal server error",
        "0x1f54b5": "Device authentication error: Under maintenance",
        "0x1f62b5": "Device authentication error: Ban",
        "0x58aca": "Npad ID is out of range",
        "0x2032ca": "ButtonConfigSettings IsFull flag is clear",
        "0x28cb": "The [6.0.0+] Authentication challenge failed",
        "0x82cb": "ResultNetworkNotFound",
        "0x84cb": "ResultConnectionTimeout",
        "0x86cb": "ResultConnectionRejected",
        "0xc2cb": "Matching LocalCommunicationId not found in the user-process control.nacp",
        "0xe2cb": "ResultLowerVersion",
        "0xe4cb": "ResultHigherVersion",
        "0xf0cd": "IrsensorNotReady",
        "0x198cd": "IR camera invalid handle value",
        "0x1a8cd": "IR camera handle pointer is null",
        "0x6ce": "AlbumWorkMemoryError",
        "0x10ce": "AlbumOutOfRange",
        "0x18ce": "AlbumInvalidTimestamp",
        "0x1ace": "AlbumInvalidStorage",
        "0x1cce": "AlbumInvalidFileContents",
        "0x2ace": "AlbumIsNotMounted",
        "0x2cce": "AlbumFileNotFound",
        "0x30ce": "AlbumInvalidFileData",
        "0x3cce": "AlbumReadBufferShortage",
        "0xaf2ce": "InternalAlbumLimitationFileCountLimit",
        "0x4da": "StatusManager entry IsValid flag not set, or controller-update currently in-progress",
        "0x6da": "Controller-update failed via the LibraryApplet",
        "0x8da": "Invalid BusHandle",
        "0xada": "StatusManager entry flag +0x0 not set, or device not connected",
        "0xeda": "PollingReceivedData not available",
        "0x10da": "StatusManager entry DeviceEnabled flag not set, or flag +0x0 not set",
        "0x12da": "ExternalDeviceId mismatch",
        "0x14da": "BusHandle already initialized",
        "0x104e7": "Nullptr passed to the LocalCommunicationId control.nacp validation func",
        "0x140e7": "GroupInfo field out of range",
        "0x142e7": "SupportedPlatform not appropriate for this operation",
        "0x146e7": "Invalid ServiceName",
        "0x148e7": "Must provide PresharedBinaryKey",
        "0x1c0e7": "Requested Priority value not allowed",
        "0x1c2e7": "Matching LocalCommunicationId not found in the user-process control.nacp",
        "0x200e7": "Invalid flag",
        "0x204e7": "Invalid SupportedPlatform",
        "0x208e7": "Invalid StaticAesKeyIndex",
        "0x20Ae7": "MemberCountMax cannot be greater than 8",
        "0x210e7": "GroupInfo+8F must be 0x20",
    }



class err(commands.Cog): 
    
    def __init__(self, bot: discord.Bot):
        self.bot = bot
        
    @slash_command(description="NX Errorcode")
    async def error(self, ctx: discord.ApplicationContext, code: str):
        code = code.lower()
    
        if code in error_codes:
            send_err_embed = discord.Embed(
            title=code,
            description=f"Description: {error_codes[code]}",
            url=wiki
            )

            send_err_embed.add_field(name="For more Details open the Switchbrew Wiki", value=wiki, inline=False)
            await ctx.respond(embed=send_err_embed, ephemeral=True)
            
            
        else:  
            send_ukn_embed = discord.Embed(
                title=code,
                description=f"Unknown Error"
            )
            
            send_ukn_embed.add_field(name="For more Details open the Switchbrew Wiki", value=wiki, inline=False)
            await ctx.respond(embed=send_ukn_embed, ephemeral=True)
            
            
def setup(bot: discord.Bot):
    bot.add_cog(err(bot))
